services:
  - type: web
    name: task-manager-backend
    env: java
    plan: free
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/taskManager-0.0.1-SNAPSHOT.jar"
